FROM node:24.6.0

WORKDIR /app

# Copiar arquivos
COPY . .

# Instalar e build
RUN npm install && npm run build

# Preparar saída
RUN mkdir -p /dist && cp -r dist/* /dist/

# Comando
CMD ["sh", "-c", "echo 'Ready' && tail -f /dev/null"] 