FROM node:24.6.0

WORKDIR /app

# Copiar arquivos
COPY . .

# Instalar dependências
RUN npm install

# Build
RUN npm run build

# Criar diretório de saída
RUN mkdir -p /dist && cp -r dist/* /dist/

# Comando
CMD ["sh", "-c", "echo 'Ready' && tail -f /dev/null"] 