FROM node:24.6.0

WORKDIR /app

# Copiar arquivos
COPY . .

# Limpar cache do npm
RUN npm cache clean --force

# Instalar dependências
RUN npm install --no-audit --no-fund

# Build da aplicação
RUN npm run build

# Preparar saída
RUN mkdir -p /dist && cp -r dist/* /dist/

# Comando
CMD ["sh", "-c", "echo 'Final build completed!' && tail -f /dev/null"] 