FROM node:24.6.0

WORKDIR /app

# Copiar arquivos
COPY . .

# Instalar dependências
RUN npm install

# Build da aplicação
RUN npm run build

# Preparar saída
RUN mkdir -p /dist && cp -r dist/* /dist/

# Comando
CMD ["sh", "-c", "echo 'Build completed!' && tail -f /dev/null"] 