FROM node:24.6.0

WORKDIR /app

# Copiar tudo
COPY . .

# Instalar dependências
RUN npm install

# Build
RUN npm run build

# Preparar saída
RUN mkdir -p /dist && cp -r dist/* /dist/

# Comando
CMD ["sh", "-c", "echo 'Frontend ready!' && tail -f /dev/null"] 