{
 "title": "CMM - Nginx",
 "refresh": "30s",
 "panels": [
  {
   "title": "Nginx Requests (rate 1m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Conexões Ativas",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 8, "h": 6 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Nginx UP",
   "type": "stat",
   "gridPos": { "x": 8, "y": 8, "w": 8, "h": 6 },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Scrapes Exporter",
   "type": "stat",
   "gridPos": { "x": 16, "y": 8, "w": 8, "h": 6 },
   "targets": [
    { "expr": "nginx_exporter_scrapes_total" }
   ]
  }
 ]
}